#!/bin/bash

# Build script to inject environment variables into firebase-config.js
# This runs during Vercel deployment

cat > frontend/firebase-config.js << EOF
// Firebase Configuration - Auto-generated from environment variables
// Do not edit this file manually

const firebaseConfig = {
  apiKey: "${FIREBASE_API_KEY}",
  authDomain: "${FIREBASE_AUTH_DOMAIN}",
  projectId: "${FIREBASE_PROJECT_ID}",
  storageBucket: "${FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${FIREBASE_APP_ID}",
  measurementId: "${FIREBASE_MEASUREMENT_ID}"
};

// Export for use in other files
window.FIREBASE_CONFIG = firebaseConfig;
EOF

echo "✅ Firebase config generated successfully"
